# Generated by Django 2.1.1 on 2018-09-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_text', models.CharField(max_length=200)),
                ('media_type', models.CharField(max_length=10)),
                ('media_url', models.FileField(upload_to='media')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QC.Material')),
            ],
        ),
    ]
