# Generated by Django 2.1.1 on 2018-10-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_auto_20181001_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='mime_type',
            field=models.CharField(max_length=32),
        ),
    ]
