# Generated by Django 2.1.1 on 2018-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0003_auto_20181001_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
