# Generated by Django 2.1.1 on 2018-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0004_material_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(default='in process', max_length=200),
        ),
    ]
